# Procura pela biblioteca ZLIB
# Módulos:
# 	ZLIB_INCLUDE_DIRS	- Diretório onde está zlib.h
# 	ZLIB_LIBRARIES	- Lista de bibliotecas da zlib.
# 	ZLIB_FOUND	- Verdadeiro, caso a biblioteca seja encontrada.

# Procura pelo diretório da biblioteca.
IF (ZLIB_INCLUDE_DIR)
  SET(ZLIB_FIND_QUIETLY TRUE)
ENDIF (ZLIB_INCLUDE_DIR)

FIND_PATH(ZLIB_INCLUDE_DIR zlib.h)

SET(ZLIB_NAMES z zlib zdll)
FIND_LIBRARY(ZLIB_LIBRARY NAMES ${ZLIB_NAMES} )
MARK_AS_ADVANCED( ZLIB_LIBRARY ZLIB_INCLUDE_DIR )

SET(ZLIB_INCLUDE_DIRS "${ZLIB_INCLUDE_DIR}")
SET(ZLIB_LIBRARIES    "${ZLIB_LIBRARY}")

INCLUDE(CheckFunctionExists)
SET(CMAKE_REQUIRED_LIBRARIES ${ZLIB_LIBRARIES})
CHECK_FUNCTION_EXISTS("gzclearerr" HAVE_GZCLEARERR)
SET(CMAKE_REQUIRED_LIBRARIES "")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ZLIB DEFAULT_MSG ZLIB_LIBRARIES ZLIB_INCLUDE_DIRS)